# Site settings
title: seanorama
email: seanorama+website@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  On the road to I don't know where.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://seanroberts.org" # the base hostname & protocol for your site
twitter_username: seano
github_username:  seanorama

# Build settings
markdown: kramdown
